kind: pipeline
type: docker
name: hexo-blog-ci

trigger:
  branch:
    - main
  event:
    - push
    - custom

clone:
  depth: 1

steps:
  - name: build
    image: node:18.15-alpine3.16
    pull: if-not-exists
    commands:
      - yarn
      - yarn build

  - name: publish
    image: plugins/gh-pages:1.3.2
    pull: if-not-exists
    environment:
      DRONE_REMOTE_URL: "git@github.com:shinobi9/hexo-blog.git"
    settings:
      pages_directory: public
      # username:
      #   from_secret: GITHUB_USERNAME
      # password:
      #   from_secret: GITHUB_PASSWORD
      ssh_key:
        from_secret: SSH_KEY