kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: deploy
    image: node:14.10.0
    environment:
      DEPLOY_KEY:
        from_secret: DEPLOY_KEY
    commands:
      - npm i
      - npm run build
      - timedatectl set-timezone "Asia/Shanghai"
      - mkdir -p ~/.ssh/ && echo "$DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - npm run deploy