kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: deploy
    image: node:14.10.0
    commands:
      - which git
      # - npm i
      # - npm run build
      # - ls -l .
      # - npm run deploy