name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile

      - name: Build site
        run: yarn build

      - name: Deploy with Hexo
        env:
          # DEPLOY_BRANCH: gh-pages
          GIT_EMAIL: ${{ secrets.EMAIL }}
          GIT_USER: ${{ secrets.USER }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: yarn deploy